#!/bin/sh

# backup the database for each supplied arg
for application in "$@"
do
    mkdir -p /data/collection/fly-db-backup/$application

    # the password is not avaliable through the fly cli, so we store it in pass
    db_password=$(pass fly-postgres-password/$application)

    # the last part of this output file name must be sortable for
    # sync-fly-db to find the latest backup
    output="/data/collection/fly-db-backup/$application/$(date +%s).dump";
    pg_dump -Fc --no-acl --no-owner postgres://postgres:$db_password@$application.internal/postgres > $output
done
