#!/bin/sh
set -o errexit
for feature_branch_name in "$@"
do
    git checkout develop
    git pull
    git checkout $feature_branch_name
    git rebase develop --exec 'git commit --amend --no-edit --date "$(date)"'
    # git push -f
done
