#!/bin/sh
# visualize the schema of whatever db is currently running using schemaspy
# this requires that schemaspy and postgresql-jdbc are installed

db_name=$(get-active-postgres-dev-database)

output_dir=$(mktemp -d)

schemaspy -dp /usr/share/java/postgresql-jdbc \
          -t pgsql \
          -host localhost \
          -port 5432 \
          -db $db_name \
          -s public \
          -u postgres \
          -p postgres \
          -o $output_dir
